env: # Environt variable to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone repo
    rclone_config: ""

task:
    name: Rom-Builder-for-certus
    timeout_in: 120m
    container:
      image: apon77/aosp:latest
      cpu: 16
      memory: 24G
    system_update_script:
      - ./system_update
    neofetch_script:
      - ./neofetch
    specification_script:
      - ./specification
#    download_ccache_script:
#      - ./download_ccache
    sync_script:
      - ./sync
    build_script:
      - ./build
    upload_ccache_script:
      - ./upload_ccache
      
