#!/bin/bash
cd /tmp/rom # Depends on where source got synced
rm -rf .repo & # lets remove unnecessary things, so that no storage issue can occur

# Normal build
. build/envsetup.sh
lunch rr_cereus
export SELINUX_IGNORE_NEVERALLOWS=true
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z

up(){
	curl --upload-file $1 https://transfer.sh/
}

make_brunch(){
	brunch cereus
	zip=$(up out/target/product/cereus/*zip)
	echo " "
	echo "$zip"
}

make_rom(){
	make bacon -j8
	zip=$(up out/target/product/cereus/*zip)
	echo " "
	echo "$zip"
}

make_brunch &
sleep 5200 && kill "$!"
