#!/bin/bash

# Lets see machine specifications and environments
df -h
free -h
nproc
cat /etc/os*
env

echo "Installing some dependencies . . . . . ."
sudo apt update && sudo apt-get --yes --force-yes install git-core gnupg wget curl flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig bc kmod

cat /etc/os*
env

url=https://twilight-sky-9953.unnamed877.workers.dev/ccache/ccache.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
time tar xf ccache.tar.gz
rm -rf ccache.tar.gz
