#!/bin/bash

cd /tmp

date=`date +%Y%m%d`

# Compress function with pigz for faster compression
com () 
{ 
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz ccache
}

time com ccache-rr-8.6.7-certus 1 # Compression level 1, its enough

mkdir -p ~/.config/rclone
echo "$rclone_config" > ~/.config/rclone/rclone.conf
time rclone copy ccache-rr-8.6.7-certus.tar.gz shalordx:/AndroidBuilder/ccache -P
